[project]
name = "ai-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = [
    "jupyter-ai[all]>=2.31.1",
    "jupyterlab>=4.3.6",
    "marimo>=0.11.25",
    "optuna>=4.2.1",
    "tensorboard>=2.19.0",
]
